import { useState } from "react";
import { Link, useSearchParams } from "react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { GitCompareArrows, Plus, ArrowLeft, CalendarOff, RefreshCw } from "lucide-react";
import { axios } from "@/configs/axios.config";
import { useUser } from "@/providers/user.provider";
import { useDataScope } from "@/hooks/useDataScope";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { WorkspaceHeader, workspacePanel } from "@/components/ui/workspace-page";

type Member = { id: string; name: string; weeklyMinutes: number | null; team: string };
type Work = { id: string; title: string; projectId: string; projectName: string; assignedTo: string | null; startDate: string | null; endDate: string | null; estimatedHours: string | null; blocked: boolean };
type Change = { key: string; type: "task" | "proposal"; taskId?: string; title?: string; assignedTo: string | null; startDate: string; endDate: string; estimatedMinutes?: number | null };
type Summary = { id: string; title: string; week_start: string; weeks: number; revision: number; state: string };
type Load = { id: string; name: string; team: string; plannedMinutes: number; availableMinutes: number | null; absenceMinutes: number | null; remainingMinutes: number | null; partial: boolean; unestimated: number; unscheduled: number; blocked: number; overloaded: boolean };
type Base = { members: Member[]; tasks: Work[]; projects: { id: string; name: string; public?: boolean; eligible: string[] }[]; hiddenTasks: number; excludedParents: number };
type Detail = { id: string; title: string; week: string; weeks: number; revision: number; state: string; stale: boolean; base: Base; changes: Change[]; appliedIds: string[]; comparison: { week: string; before: { unassigned: number; members: Load[] }; after: { unassigned: number; members: Load[] } }[] };
type Absence = { id: string; userId: string; startDate: string; endDate: string; kind: string; revision: number };
const field = "mt-1 block w-full min-w-0 rounded-md border border-border bg-background p-2 text-sm focus-visible:outline-2 focus-visible:outline-[#1797ba]";
const path = "/capacity-scenarios";
function errorCode(error: unknown) { return (error as { response?: { data?: { code?: string } } })?.response?.data?.code || "FAILED"; }
function useRefresh() { const cache = useQueryClient(); return () => { for (const key of ["scenarios", "scenario", "capacity-absences", "capacity"]) void cache.invalidateQueries({ queryKey: [key] }); }; }
function ErrorNotice({ error }: { error: unknown }) { const { t } = useTranslation(); return <p role="alert" className="text-sm text-destructive">{t(`scenarios.errors.${errorCode(error)}`, { defaultValue: t("scenarios.errors.FAILED") })}</p>; }

export default function CapacityScenariosPage() {
  const { t } = useTranslation(); const { data } = useUser(); const scope = useDataScope(); const [params, setParams] = useSearchParams(); const [creating, setCreating] = useState(false); const [tab, setTab] = useState("scenarios");
  const user = data?.user; const allowed = !!user && (["superadmin", "subadmin"].includes(user.role) || user.role === "user" && (user.isOrganizationOwner || user.isOrganizationManager));
  const query = useQuery({ queryKey: ["scenarios", scope], enabled: !!allowed, queryFn: async () => (await axios.get<{ data: Summary[] }>(path)).data.data });
  const selected = query.data?.find(r => r.id === params.get("id"));
  if (!allowed) return <p className="p-6">{t("scenarios.forbidden")}</p>;
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 text-foreground sm:px-6">
    <Link to="/dashboard/team-capacity" className="inline-flex items-center gap-2 text-sm text-[#11718c] hover:underline dark:text-[#55bdd9]"><ArrowLeft aria-hidden="true" className="size-4 rtl:rotate-180" />{t("scenarios.back")}</Link>
    <WorkspaceHeader icon={GitCompareArrows} title={t("scenarios.title")} description={t("scenarios.description")} actions={<Button onClick={() => setCreating(true)}><Plus aria-hidden="true" className="size-4" />{t("scenarios.create")}</Button>} />
    <div className="flex flex-wrap gap-2 border-b border-border pb-3">{["scenarios", "absences"].map(v => <Button key={v} variant={tab === v ? "default" : "ghost"} aria-pressed={tab === v} onClick={() => setTab(v)}>{v === "absences" && <CalendarOff aria-hidden="true" className="size-4" />}{t(`scenarios.${v}`)}</Button>)}</div>
    {tab === "absences" ? <Absences /> : <>
      <label className="block max-w-xl text-sm">{t("scenarios.select")}<select className={field} value={params.get("id") || ""} onChange={e => setParams(e.target.value ? { id: e.target.value } : {})}><option value="">{t("scenarios.choose")}</option>{query.data?.map(r => <option key={r.id} value={r.id}>{r.title} · {t(`scenarios.${r.state}`)}</option>)}</select></label>
      {query.isPending ? <p role="status">{t("scenarios.loading")}</p> : query.isError ? <ErrorNotice error={query.error} /> : selected ? <ScenarioWorkspace key={`${scope}:${selected.id}`} summary={selected} /> : <div className={`${workspacePanel} space-y-3 p-8`}><h2 className="font-medium">{t("scenarios.empty")}</h2><p className="text-sm text-muted-foreground">{t("scenarios.emptyNote")}</p></div>}
    </>}
    {creating && <CreateScenario close={() => setCreating(false)} opened={id => { setParams({ id }); setTab("scenarios"); setCreating(false); }} />}
  </main>;
}
function CreateScenario({ close, opened }: { close: () => void; opened: (id: string) => void }) {
  const { t } = useTranslation(); const refresh = useRefresh(); const [id] = useState(crypto.randomUUID()); const [title, setTitle] = useState(""); const [week, setWeek] = useState(new Date().toISOString().slice(0, 10)); const [weeks, setWeeks] = useState(4);
  const mutation = useMutation({ mutationFn: () => axios.post(path, { id, title, week, weeks }), onSuccess: () => { refresh(); opened(id); } });
  return <Dialog open onOpenChange={v => { if (!v && !mutation.isPending) close(); }}><DialogContent><DialogHeader><DialogTitle>{t("scenarios.create")}</DialogTitle><DialogDescription>{t("scenarios.createNote")}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); mutation.mutate(); }}><fieldset disabled={mutation.isPending} className="space-y-4"><label className="block text-sm">{t("scenarios.name")}<Input required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block text-sm">{t("scenarios.week")}<Input required type="date" value={week} onChange={e => setWeek(e.target.value)} /></label><label className="block text-sm">{t("scenarios.weeks")}<Input type="number" required min={1} max={12} value={weeks} onChange={e => setWeeks(Number(e.target.value))} /></label><Button type="submit">{t("scenarios.create")}</Button></fieldset>{mutation.isError && <ErrorNotice error={mutation.error} />}</form></DialogContent></Dialog>;
}
export function ScenarioWorkspace({ summary }: { summary: Summary }) {
  const { t, i18n } = useTranslation(); const scope = useDataScope(); const refresh = useRefresh(); const [editing, setEditing] = useState<Change | "task" | "proposal" | null>(null); const [selected, setSelected] = useState<string[]>([]); const [confirmed, setConfirmed] = useState(false); const [reviewedRevision, setReviewedRevision] = useState<number | null>(null); const [editRevision, setEditRevision] = useState(0); const [resetRevision, setResetRevision] = useState<number | null>(null); const [resetConfirmed, setResetConfirmed] = useState(false); const [weekIndex, setWeekIndex] = useState(0); const [memberId, setMemberId] = useState(""); const [key, setKey] = useState(crypto.randomUUID());
  const url = `${path}/${encodeURIComponent(summary.id)}`;
  const query = useQuery({ queryKey: ["scenario", scope, summary.id], queryFn: async () => (await axios.get<{ data: Detail }>(url)).data.data }); const d = query.data;
  const apply = useMutation({ mutationFn: () => axios.post(`${url}/apply`, { key, revision: reviewedRevision, selected, confirm: true }), onSettled: refresh });
  const reset = useMutation({ mutationFn: () => axios.post(`${url}/refresh`, { revision: resetRevision, confirm: true }), onSuccess: () => { setSelected([]); setConfirmed(false); setResetConfirmed(false); }, onSettled: refresh });
  const remove = useMutation({ mutationFn: () => axios.delete(url, { data: { revision: resetRevision } }), onSettled: refresh });
  const save = useMutation({ mutationFn: ({ changes, revision }: { changes: Change[]; revision: number }) => axios.put(url, { revision, changes }), onSuccess: () => { setEditing(null); setSelected([]); setConfirmed(false); setKey(crypto.randomUUID()); }, onSettled: refresh });
  const hours = (n: number | null) => n === null ? t("scenarios.unknown") : `${(n / 60).toLocaleString(i18n.language, { maximumFractionDigits: 2 })} h`;
  const busy = apply.isPending || reset.isPending || remove.isPending || save.isPending;
  const editable = !!d && d.state === "draft" && !d.stale && !busy;
  const comparison = d?.comparison[weekIndex];
  return <div className="space-y-5">
    {query.isPending && <p role="status">{t("scenarios.loading")}</p>}{query.isError && <ErrorNotice error={query.error} />}
    {d && <>
      <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{d.title}</h2><p className="mt-1 text-sm text-muted-foreground">{t(`scenarios.${d.state}`)} · <span dir="ltr">{d.week} · UTC</span></p></div><Button variant="outline" disabled={query.isFetching || busy} onClick={() => void query.refetch()}><RefreshCw aria-hidden="true" className="size-4" />{t("scenarios.reload")}</Button></header>
      {d.stale && d.state === "draft" && <p role="status" className="rounded-lg border border-amber-500/40 bg-amber-500/5 p-4 text-sm">{t("scenarios.stale")}</p>}
      {d.state === "applied" && <p role="status" className="rounded-lg border border-[#1797ba]/30 bg-[#1797ba]/5 p-4 text-sm">{t("scenarios.appliedNote", { count: d.appliedIds.length })}</p>}
      <p className="text-sm leading-relaxed text-muted-foreground">{t("scenarios.method")}</p>
      {!!d.base.hiddenTasks && <p className="text-sm text-amber-700 dark:text-amber-300">{t("scenarios.hidden")}</p>}
      {!!d.base.excludedParents && <p className="text-sm text-muted-foreground">{t("scenarios.parents", { count: d.base.excludedParents })}</p>}
      <section className={`${workspacePanel} overflow-hidden`}><header className="flex flex-wrap items-end gap-3 border-b border-border bg-secondary/25 p-4"><h3 className="me-auto font-medium">{t("scenarios.comparison")}</h3><label className="text-xs">{t("scenarios.week")}<select className={field} value={weekIndex} onChange={e => setWeekIndex(Number(e.target.value))}>{d.comparison.map((w, i) => <option key={w.week} value={i}>{w.week}</option>)}</select></label><label className="text-xs">{t("scenarios.person")}<select className={field} value={memberId} onChange={e => setMemberId(e.target.value)}><option value="">{t("scenarios.all")}</option>{d.base.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></header>
        {!!comparison?.after.unassigned && <p className="px-4 pt-4 text-sm text-amber-700 dark:text-amber-300">{t("scenarios.unassigned", { count: comparison.after.unassigned })}</p>}
        <p className="px-4 pt-3 text-xs text-muted-foreground sm:hidden">{t("scenarios.scrollComparison")}</p><div className="overflow-x-auto" role="region" aria-label={t("scenarios.comparison")} tabIndex={0}><table className="w-full min-w-[660px] text-start text-sm"><caption className="sr-only">{t("scenarios.comparison")}</caption><thead className="border-b border-border text-muted-foreground"><tr>{["person", "available", "before", "after", "remaining"].map(k => <th key={k} className="p-4 text-start font-medium">{t(`scenarios.${k}`)}</th>)}</tr></thead><tbody className="divide-y divide-border">{comparison?.after.members.filter(m => !memberId || m.id === memberId).slice(0, 100).map(m => <tr key={m.id} className={m.overloaded ? "bg-amber-500/5" : ""}><th className="p-4 text-start font-medium">{m.name}<span className="block text-xs font-normal text-muted-foreground">{m.team}</span>{m.partial && <span className="block text-xs font-normal text-amber-700 dark:text-amber-300">{t("scenarios.partial", { estimates: m.unestimated, dates: m.unscheduled })}</span>}{!!m.blocked && <span className="block text-xs font-normal text-muted-foreground">{t("scenarios.blocked", { count: m.blocked })}</span>}</th><td className="p-4 tabular-nums">{hours(m.availableMinutes)}{!!m.absenceMinutes && <span className="block text-xs text-muted-foreground">{t("scenarios.absent", { hours: hours(m.absenceMinutes) })}</span>}</td><td className="p-4 tabular-nums">{hours(comparison.before.members.find(v => v.id === m.id)?.plannedMinutes ?? 0)}</td><td className="p-4 font-semibold tabular-nums text-[#11718c] dark:text-[#55bdd9]">{hours(m.plannedMinutes)}{m.overloaded && <span className="block text-xs text-amber-700 dark:text-amber-300">{t("scenarios.overloaded")}</span>}</td><td className="p-4 tabular-nums">{hours(m.remainingMinutes)}</td></tr>)}</tbody></table></div>{!memberId && d.base.members.length > 100 && <p className="p-4 text-xs">{t("scenarios.memberLimit")}</p>}
      </section>
      <section className={`${workspacePanel} space-y-4 p-5`}><header className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-medium">{t("scenarios.changes")}</h3>{d.state === "draft" && <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!editable || d.changes.length >= 100} onClick={() => { setEditRevision(d.revision); setEditing("task"); }}>{t("scenarios.moveTask")}</Button><Button variant="outline" disabled={!editable || d.changes.length >= 100} onClick={() => { setEditRevision(d.revision); setEditing("proposal"); }}>{t("scenarios.newWork")}</Button></div>}</header>
        {!d.changes.length && <p className="text-sm text-muted-foreground">{t("scenarios.noChanges")}</p>}
        <ul className="divide-y divide-border">{d.changes.map(c => { const source = d.base.tasks.find(w => w.id === c.taskId); return <li key={c.key} className="flex flex-wrap items-start gap-3 py-4">{d.state === "draft" && c.type === "task" && <input aria-label={`${t("scenarios.selectChange")} ${source?.title}`} className="mt-1" type="checkbox" disabled={!editable} checked={selected.includes(c.key)} onChange={e => { setSelected(v => e.target.checked ? [...v, c.key] : v.filter(k => k !== c.key)); setConfirmed(false); setKey(crypto.randomUUID()); }} />}<div className="min-w-0 flex-1 basis-[calc(100%-2rem)] space-y-1 sm:basis-0"><p className="break-words text-sm font-medium">{source ? `${source.projectName} · ${source.title}` : c.title}</p>{source && <p className="text-xs text-muted-foreground">{t("scenarios.before")}: {source.startDate || "—"} → {source.endDate || "—"} · {d.base.members.find(m => m.id === source.assignedTo)?.name || t("scenarios.noPerson")}</p>}<p className="text-xs">{t("scenarios.after")}: {c.startDate} → {c.endDate} · {d.base.members.find(m => m.id === c.assignedTo)?.name || t("scenarios.noPerson")}</p>{c.type === "proposal" && <p className="text-xs text-muted-foreground">{t("scenarios.proposalOnly")} · {hours(c.estimatedMinutes ?? null)}</p>}</div>{d.state === "draft" && <div className="ms-auto flex gap-1 sm:ms-0"><Button size="sm" variant="ghost" disabled={!editable} onClick={() => { setEditRevision(d.revision); setEditing(c); }}>{t("scenarios.edit")}</Button><Button size="sm" variant="ghost" disabled={!editable} onClick={() => save.mutate({ revision: d.revision, changes: d.changes.filter(v => v.key !== c.key) })}>{t("scenarios.remove")}</Button></div>}</li>; })}</ul>
        {d.state === "draft" && !!d.changes.length && <div className="space-y-3 border-t border-border pt-4"><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} disabled={!editable || !selected.length} onChange={e => { setConfirmed(e.target.checked); setReviewedRevision(d.revision); }} />{t("scenarios.confirmApply")}</label><Button disabled={!editable || !confirmed || !selected.length || reviewedRevision !== d.revision} onClick={() => apply.mutate()}>{t("scenarios.apply", { count: selected.length })}</Button></div>}
      </section>
    </>}
    {(d?.state ?? summary.state) === "draft" && <details className="rounded-lg border border-border p-4"><summary className="cursor-pointer text-sm">{t("scenarios.manageDraft")}</summary><p className="my-3 text-xs text-muted-foreground">{t("scenarios.resetNote")}</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={resetConfirmed} disabled={busy} onChange={e => { setResetConfirmed(e.target.checked); setResetRevision(d?.revision ?? summary.revision); }} />{t("scenarios.confirmReset")}</label><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={!resetConfirmed || busy || resetRevision !== (d?.revision ?? summary.revision)} onClick={() => reset.mutate()}>{t("scenarios.reset")}</Button><Button variant="outline" disabled={!resetConfirmed || busy || resetRevision !== (d?.revision ?? summary.revision)} onClick={() => remove.mutate()}>{t("scenarios.deleteDraft")}</Button></div></details>}
    {[save, apply, reset, remove].map((m, i) => m.isError && <ErrorNotice key={i} error={m.error} />)}
    {editing && d && <ChangeDialog key={typeof editing === "string" ? editing : editing.key} value={editing} base={d.base} existing={d.changes} week={d.week} saving={save.isPending} error={save.error} close={() => setEditing(null)} saved={v => save.mutate({ revision: editRevision, changes: [...d.changes.filter(c => c.key !== v.key), v] })} />}
  </div>;
}
function ChangeDialog({ value, base, existing, week, saving, error, close, saved }: { value: Change | "task" | "proposal"; base: Base; existing: Change[]; week: string; saving: boolean; error: unknown; close: () => void; saved: (v: Change) => void }) {
  const { t } = useTranslation(); const original = typeof value === "string" ? null : value; const type = typeof value === "string" ? value : value.type; const [key] = useState(original?.key || crypto.randomUUID()); const [taskId, setTaskId] = useState(original?.taskId || ""); const [title, setTitle] = useState(original?.title || ""); const [assignedTo, setAssignedTo] = useState(original?.assignedTo || ""); const [startDate, setStartDate] = useState(original?.startDate || week); const [endDate, setEndDate] = useState(original?.endDate || week); const [hours, setHours] = useState(original?.estimatedMinutes == null ? "" : String(original.estimatedMinutes / 60));
  const task = base.tasks.find(v => v.id === taskId); const project = base.projects.find(p => p.id === task?.projectId); const eligible = type === "proposal" || project?.public ? base.members.map(m => m.id) : project?.eligible ?? [];
  return <Dialog open onOpenChange={v => { if (!v && !saving) close(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{t(type === "task" ? "scenarios.moveTask" : "scenarios.newWork")}</DialogTitle><DialogDescription>{t(type === "task" ? "scenarios.moveNote" : "scenarios.proposalOnly")}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); saved(type === "task" ? { key, type, taskId, assignedTo: assignedTo || null, startDate, endDate } : { key, type, title, assignedTo: assignedTo || null, startDate, endDate, estimatedMinutes: hours === "" ? null : Math.round(Number(hours) * 60) }); }}><fieldset disabled={saving} className="space-y-4">
    {type === "task" ? <label className="block text-sm">{t("scenarios.task")}<select className={field} required value={taskId} onChange={e => { setTaskId(e.target.value); const w = base.tasks.find(v => v.id === e.target.value); if (w) { setAssignedTo(w.assignedTo || ""); setStartDate(w.startDate || week); setEndDate(w.endDate || week); } }}><option value="">{t("scenarios.choose")}</option>{base.tasks.filter(w => !existing.some(c => c.taskId === w.id && c.key !== key)).map(w => <option key={w.id} value={w.id}>{w.projectName} · {w.title}</option>)}</select></label> : <><label className="block text-sm">{t("scenarios.workTitle")}<Input required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block text-sm">{t("scenarios.estimate")}<Input type="number" min={0} max={10000} step="0.01" value={hours} onChange={e => setHours(e.target.value)} /></label></>}
    <label className="block text-sm">{t("scenarios.person")}<select className={field} value={assignedTo} onChange={e => setAssignedTo(e.target.value)}><option value="">{t("scenarios.noPerson")}</option>{base.members.filter(m => eligible.includes(m.id)).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">{t("scenarios.start")}<Input type="date" required value={startDate} onChange={e => setStartDate(e.target.value)} /></label><label className="block text-sm">{t("scenarios.end")}<Input type="date" required min={startDate} value={endDate} onChange={e => setEndDate(e.target.value)} /></label></div><Button type="submit">{t("scenarios.save")}</Button></fieldset>{!!error && <ErrorNotice error={error} />}</form></DialogContent></Dialog>;
}
function Absences() {
  const { t } = useTranslation(); const scope = useDataScope(); const refresh = useRefresh(); const [id, setId] = useState(crypto.randomUUID()); const [userId, setUserId] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [kind, setKind] = useState("vacation");
  const query = useQuery({ queryKey: ["capacity-absences", scope], queryFn: async () => (await axios.get<{ data: { members: Member[]; items: Absence[] } }>(`${path}/absences`)).data.data });
  const create = useMutation({ mutationFn: () => axios.post(`${path}/absences`, { id, userId, startDate, endDate, kind }), onSuccess: () => { setId(crypto.randomUUID()); setStartDate(""); setEndDate(""); refresh(); } });
  const remove = useMutation({ mutationFn: (a: Absence) => axios.delete(`${path}/absences/${encodeURIComponent(a.id)}`, { data: { revision: a.revision } }), onSettled: refresh });
  return <section className={`${workspacePanel} space-y-5 p-5`}><h2 className="font-medium">{t("scenarios.absences")}</h2><p className="text-sm leading-relaxed text-muted-foreground">{t("scenarios.absenceNote")}</p><form onSubmit={e => { e.preventDefault(); create.mutate(); }}><fieldset disabled={query.isPending || create.isPending} className="grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="min-w-0 text-sm">{t("scenarios.person")}<select className={field} required value={userId} onChange={e => setUserId(e.target.value)}><option value="">{t("scenarios.choose")}</option>{query.data?.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="text-sm">{t("scenarios.start")}<Input type="date" required value={startDate} onChange={e => setStartDate(e.target.value)} /></label><label className="text-sm">{t("scenarios.end")}<Input type="date" required min={startDate} value={endDate} onChange={e => setEndDate(e.target.value)} /></label><label className="text-sm">{t("scenarios.kind")}<select className={field} value={kind} onChange={e => setKind(e.target.value)}>{["vacation", "unavailable"].map(v => <option key={v} value={v}>{t(`scenarios.${v}`)}</option>)}</select></label><Button type="submit">{t("scenarios.addAbsence")}</Button></fieldset></form>
    {query.isPending && <p role="status">{t("scenarios.loading")}</p>}{query.isError && <ErrorNotice error={query.error} />}{create.isError && <ErrorNotice error={create.error} />}{remove.isError && <ErrorNotice error={remove.error} />}
    <ul className="divide-y divide-border">{query.data?.items.map(a => <li key={a.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="break-words text-sm font-medium">{query.data.members.find(m => m.id === a.userId)?.name || t("scenarios.inactive")}</p><p className="text-xs text-muted-foreground">{a.startDate} → {a.endDate} · {t(`scenarios.${a.kind}`)} · UTC</p></div><Button variant="ghost" size="sm" disabled={remove.isPending} onClick={() => remove.mutate(a)}>{t("scenarios.remove")}</Button></li>)}</ul>{query.data?.items.length === 0 && <p className="text-sm text-muted-foreground">{t("scenarios.noAbsences")}</p>}
  </section>;
}
