import { act, cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router";
import CapacityScenariosPage, { ScenarioWorkspace } from "./capacity-scenarios.page";
import messages from "@/locales/scenarios/en.json";
const api = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn(), put: vi.fn(), delete: vi.fn(), role: "user", owner: true }));
vi.mock("@/configs/axios.config", () => ({ axios: api }));
vi.mock("@/providers/user.provider", () => ({ useUser: () => ({ data: { user: { id: "owner", role: api.role, isOrganizationOwner: api.owner } } }) }));
vi.mock("@/hooks/useDataScope", () => ({ useDataScope: () => "scope" }));
vi.mock("react-i18next", () => ({ useTranslation: () => ({ i18n: { language: "en" }, t: (key: string, opts: Record<string, unknown> = {}) => { let value = key.split(".").slice(1).reduce<unknown>((v, k) => v && typeof v === "object" ? (v as Record<string, unknown>)[k] : undefined, messages) ?? opts.defaultValue ?? key; for (const [k, v] of Object.entries(opts)) value = String(value).split(`{{${k}}}`).join(String(v)); return value; } }) }));
const summary = { id: "scenario", title: "October", week_start: "2026-09-21", weeks: 1, revision: 1, state: "draft" };
const change = { key: "change", type: "task", taskId: "task", assignedTo: "owner", startDate: "2026-09-28", endDate: "2026-10-04" };
function fixture() { const member = { id: "owner", name: "Ana", team: "Design", plannedMinutes: 420, availableMinutes: null, absenceMinutes: null, remainingMinutes: null, partial: true, unestimated: 1, unscheduled: 0, blocked: 1, overloaded: false }; return { id: "scenario", title: "October", week: "2026-09-21", weeks: 1, revision: 1, state: "draft", stale: false, appliedIds: [], base: { members: [{ id: "owner", name: "Ana", team: "Design", weeklyMinutes: null }], projects: [{ id: "project", name: "Website", eligible: ["owner"] }], tasks: [{ id: "task", title: "Design", projectId: "project", projectName: "Website", assignedTo: "owner", startDate: "2026-09-21", endDate: "2026-09-27", estimatedHours: "7", blocked: true }], hiddenTasks: 0, excludedParents: 0 }, changes: [change], comparison: [{ week: "2026-09-21", before: { unassigned: 0, members: [member] }, after: { unassigned: 0, members: [{ ...member, plannedMinutes: 0 }] } }] }; }
let detail = fixture();
const clients: QueryClient[] = [];
afterEach(() => { cleanup(); for (const c of clients.splice(0)) c.clear(); });
beforeEach(() => { vi.clearAllMocks(); api.role = "user"; api.owner = true; detail = fixture(); api.get.mockImplementation(async (url: string) => ({ data: { data: url.endsWith("/absences") ? { members: detail.base.members, items: [] } : url === "/capacity-scenarios" ? [summary] : detail } })); api.post.mockResolvedValue({ data: {} }); api.put.mockResolvedValue({ data: {} }); api.delete.mockResolvedValue({ data: {} }); });
function setup(full = false) { const cache = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); clients.push(cache); render(<QueryClientProvider client={cache}><MemoryRouter initialEntries={["/dashboard/team-capacity/scenarios?id=scenario"]}>{full ? <CapacityScenariosPage /> : <ScenarioWorkspace summary={summary} />}</MemoryRouter></QueryClientProvider>); return { user: userEvent.setup(), cache }; }
it("comparison is read only and unknown capacity is never displayed as free time", async () => { setup(); await screen.findByRole("table"); expect(screen.getAllByText(messages.unknown).length).toBeGreaterThanOrEqual(2); expect(api.post).not.toHaveBeenCalled(); expect(api.put).not.toHaveBeenCalled(); });
it("applying requires selecting a change and confirming its displayed revision", async () => { const { user } = setup(); const button = await screen.findByRole("button", { name: "Apply 0 selected changes" }); expect(button).toBeDisabled(); await user.click(screen.getByLabelText("Apply change to Design")); expect(screen.getByRole("button", { name: "Apply 1 selected changes" })).toBeDisabled(); await user.click(screen.getByLabelText(messages.confirmApply)); await user.click(screen.getByRole("button", { name: "Apply 1 selected changes" })); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/capacity-scenarios/scenario/apply", expect.objectContaining({ revision: 1, selected: ["change"], confirm: true, key: expect.any(String) }))); });
it("a new server revision invalidates a confirmation from an earlier view", async () => { const { user, cache } = setup(); await user.click(await screen.findByLabelText("Apply change to Design")); await user.click(screen.getByLabelText(messages.confirmApply)); await act(async () => { cache.setQueryData(["scenario", "scope", "scenario"], { ...detail, revision: 2 }); }); await waitFor(() => expect(screen.getByRole("button", { name: "Apply 1 selected changes" })).toBeDisabled()); expect(api.post).not.toHaveBeenCalled(); });
it("stale source plans block editing and require explicit refresh", async () => { detail.stale = true; const { user } = setup(); expect(await screen.findByRole("button", { name: messages.moveTask })).toBeDisabled(); await user.click(screen.getByText(messages.manageDraft)); expect(screen.getByRole("button", { name: messages.reset })).toBeDisabled(); await user.click(screen.getByLabelText(messages.confirmReset)); await user.click(screen.getByRole("button", { name: messages.reset })); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/capacity-scenarios/scenario/refresh", { revision: 1, confirm: true })); });
it("editing a task only saves its proposal and never applies it", async () => { const { user } = setup(); await user.click(await screen.findByRole("button", { name: messages.edit })); const dialog = within(screen.getByRole("dialog")); await user.clear(dialog.getByLabelText(messages.start)); await user.type(dialog.getByLabelText(messages.start), "2026-09-29"); await user.click(dialog.getByRole("button", { name: messages.save })); await waitFor(() => expect(api.put).toHaveBeenCalledWith("/capacity-scenarios/scenario", { revision: 1, changes: [expect.objectContaining({ key: "change", startDate: "2026-09-29" })] })); expect(api.post).not.toHaveBeenCalled(); });
it("hypothetical work saves unknown estimates without creating actual projects", async () => { const { user } = setup(); await user.click(await screen.findByRole("button", { name: messages.newWork })); const dialog = within(screen.getByRole("dialog")); await user.type(dialog.getByLabelText(messages.workTitle), "New portal"); await user.click(dialog.getByRole("button", { name: messages.save })); await waitFor(() => expect(api.put).toHaveBeenCalledWith("/capacity-scenarios/scenario", expect.objectContaining({ changes: expect.arrayContaining([expect.objectContaining({ type: "proposal", title: "New portal", estimatedMinutes: null, assignedTo: null })]) }))); expect(api.post).not.toHaveBeenCalled(); });
it("an application conflict is visible without retry or success feedback", async () => { api.post.mockRejectedValue({ response: { data: { code: "PLAN_CHANGED" } } }); const { user } = setup(); await user.click(await screen.findByLabelText("Apply change to Design")); await user.click(screen.getByLabelText(messages.confirmApply)); await user.click(screen.getByRole("button", { name: "Apply 1 selected changes" })); expect(await screen.findByRole("alert")).toHaveTextContent(messages.errors.PLAN_CHANGED); expect(api.post).toHaveBeenCalledTimes(1); });
it("absence entry sends explicit person and calendar dates", async () => { const { user } = setup(true); await user.click(await screen.findByRole("button", { name: messages.absences })); await user.selectOptions(screen.getByLabelText(messages.person), "owner"); await user.type(screen.getByLabelText(messages.start), "2026-10-01"); await user.type(screen.getByLabelText(messages.end), "2026-10-07"); await user.click(screen.getByRole("button", { name: messages.addAbsence })); await waitFor(() => expect(api.post).toHaveBeenCalledWith("/capacity-scenarios/absences", expect.objectContaining({ userId: "owner", startDate: "2026-10-01", endDate: "2026-10-07", kind: "vacation" }))); });
it("ordinary members do not fetch planning snapshots", () => { api.owner = false; setup(true); expect(screen.getByText(messages.forbidden)).toBeInTheDocument(); expect(api.get).not.toHaveBeenCalled(); });
