import { useState } from "react";
import { Link, useParams, useSearchParams } from "react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { ClipboardList, Plus, ArrowLeft, ArrowUpRight, FileQuestion, FileUp, CheckCheck, Clock3, RefreshCw, Paperclip } from "lucide-react";
import { axios } from "@/configs/axios.config";
import { useUser } from "@/providers/user.provider";
import { useDataScope } from "@/hooks/useDataScope";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { WorkspaceHeader, workspacePanel } from "@/components/ui/workspace-page";

type Question = { id: string; label: string; type: "text" | "choice"; required: boolean; options: string[] };
type Attachment = { id: string; versionId: string; name: string; url: string };
export type PendingItem = { id: string; kind: string; title: string; state: string; sourceState: string; projectId: string; projectName: string; responsible: string | null; dueAt: string | null; dueDate: string | null; timezone: string; blocked: boolean; stale: boolean; href: string | null };
type Report = { items: PendingItem[]; hasMore: boolean; canManage: boolean; project: { id: string; name: string; clientId: string | null } | null; summary: { open: number; answered: number; overdue: number; responseHours: string | null } };
type Request = { id: string; title: string; description: string; kind: string; state: string; revision: number; cycle: number; questions: Question[]; due_date: string | null; timezone: string; project_id: string; client_id: string; reason: string | null; reminder_hours: number };
type Detail = { request: Request; project: { id: string; name: string; clientId: string }; dependencies: { id: string; title: string; state: string }[]; blocked: boolean; stale: boolean; canManage: boolean; canRespond: boolean; hasMoreResponses: boolean; responses: { id: string; cycle: number; message: string; answers: Record<string, string>; attachments: Attachment[]; created_at: string }[]; events: { id: string; action: string; actor: string; reason: string; created_at: string }[]; reminders: { id: string; outcome: string; created_at: string }[] };
const field = "mt-1 block w-full min-w-0 rounded-md border border-border bg-background p-2 text-sm focus-visible:outline-2 focus-visible:outline-[#1797ba]";
const kinds = ["all", "delivery", "scope", "briefing", "question", "file"];
const badge = "rounded-md border border-border bg-secondary/40 px-2 py-1 text-xs";
const area = "max-h-[90dvh] overflow-y-auto sm:max-w-2xl";

export default function ClientPendingPage() {
  const { id } = useParams(); const [search, setSearch] = useSearchParams(); const { data } = useUser(); const { t, i18n } = useTranslation(); const scope = useDataScope();
  const user = data?.user; const portal = user?.role === "client"; const allowed = user && (portal || ["superadmin", "subadmin"].includes(user.role) || (user.role === "user" && (user.isOrganizationOwner || user.isOrganizationManager)));
  const projectId = id || search.get("projectId") || undefined; const selected = search.get("requestId");
  const [page, setPage] = useState(1); const [state, setState] = useState("open"); const [kind, setKind] = useState("all"); const [overdue, setOverdue] = useState(false); const [creating, setCreating] = useState(false);
  const query = useQuery({ queryKey: ["client-pending", scope, projectId, page, state, kind, overdue], enabled: !!allowed, queryFn: async ({ signal }) => (await axios.get<{ data: Report }>("/client-pending", { params: { projectId, page, state, kind, overdue: String(overdue) }, signal })).data.data });
  const select = (requestId: string | null) => { const next = new URLSearchParams(search); if (requestId) next.set("requestId", requestId); else next.delete("requestId"); setSearch(next); };
  if (!allowed) return <p className="p-6">{t("pending.forbidden")}</p>;
  const report = query.data;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 text-foreground sm:px-6">
    {projectId && <Link className="inline-flex items-center gap-2 text-sm text-[#11718c] hover:underline dark:text-[#55bdd9]" to={`${portal ? "/clients/projects/view/" : "/dashboard/project/view/"}${encodeURIComponent(projectId)}`}><ArrowLeft aria-hidden="true" className="size-4 rtl:rotate-180" />{t("pending.back")}</Link>}
    <WorkspaceHeader icon={ClipboardList} title={t(portal ? "pending.portalTitle" : "pending.teamTitle")} description={report?.project?.name || t("pending.description")} actions={report?.canManage && projectId ? <Button disabled={!report.project?.clientId} onClick={() => setCreating(true)}><Plus aria-hidden="true" className="size-4" />{t("pending.create")}</Button> : undefined} />
    {report && <dl className="flex flex-wrap gap-x-8 gap-y-3 border-b border-border pb-4 text-sm">{([['open', report.summary.open], ['answered', report.summary.answered], ['overdue', report.summary.overdue]] as const).map(([key, value]) => <div key={key} className="flex items-baseline gap-2"><dt className="text-muted-foreground">{t(`pending.${key}`)}</dt><dd className="text-lg font-semibold tabular-nums">{value}</dd></div>)}<div className="flex items-baseline gap-2"><dt className="text-muted-foreground">{t("pending.responseTime")}</dt><dd className="font-medium tabular-nums">{report.summary.responseHours === null ? "—" : `${Number(report.summary.responseHours).toLocaleString(i18n.language)} h`}</dd></div></dl>}
    <section className={`${workspacePanel} overflow-hidden`} aria-label={t("pending.queue")}>
      <div className="flex flex-wrap items-end gap-3 border-b border-border bg-secondary/20 p-4">
        <label className="min-w-0 text-xs">{t("pending.state")}<select className={field} value={state} onChange={e => { setState(e.target.value); setPage(1); }}>{["open", "answered", "completed", "cancelled", "all"].map(v => <option key={v} value={v}>{t(`pending.${v}`)}</option>)}</select></label>
        <label className="min-w-0 text-xs">{t("pending.kind")}<select className={field} value={kind} onChange={e => { setKind(e.target.value); setPage(1); }}>{kinds.map(v => <option key={v} value={v}>{t(`pending.${v}`)}</option>)}</select></label>
        <label className="flex min-h-9 items-center gap-2 text-sm"><input type="checkbox" checked={overdue} onChange={e => { setOverdue(e.target.checked); setPage(1); }} />{t("pending.onlyOverdue")}</label>
        <Button variant="ghost" className="ms-auto" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw aria-hidden="true" className="size-4" />{t("pending.refresh")}</Button>
      </div>
      {query.isPending ? <p role="status" className="p-8">{t("pending.loading")}</p> : query.isError ? <p role="alert" className="p-6 text-sm text-destructive">{t("pending.error")}</p> : report?.items.length ? <ul className="divide-y divide-border">{report.items.map(item => <PendingRow key={`${item.kind}:${item.id}`} item={item} open={() => select(item.id)} />)}</ul> : <div className="space-y-3 px-6 py-14 text-center"><CheckCheck aria-hidden="true" className="mx-auto size-9 text-[#1797ba]" /><h2 className="font-medium">{t("pending.empty")}</h2><p className="text-sm text-muted-foreground">{t("pending.emptyHint")}</p></div>}
      <nav className="flex items-center justify-between gap-3 border-t border-border p-4" aria-label={t("pending.pagination")}><Button variant="outline" disabled={page === 1 || query.isFetching} onClick={() => setPage(page - 1)}>{t("pending.previous")}</Button><span className="text-sm tabular-nums">{page}</span><Button variant="outline" disabled={!report?.hasMore || query.isFetching} onClick={() => setPage(page + 1)}>{t("pending.next")}</Button></nav>
    </section>
    <p className="text-xs leading-relaxed text-muted-foreground">{t("pending.sourceNote")}</p>
    {selected && <RequestDialog key={`${scope}:${selected}`} id={selected} close={() => select(null)} />}
    {creating && projectId && user && <CreateDialog projectId={projectId} userId={user.id} close={() => setCreating(false)} />}
  </main>;
}
export function PendingRow({ item, open }: { item: PendingItem; open: () => void }) {
  const { t, i18n } = useTranslation(); const Icon = item.kind === "file" ? FileUp : item.kind === "question" ? FileQuestion : ClipboardList;
  const due = item.dueDate ? new Intl.DateTimeFormat(i18n.language, { dateStyle: "medium", timeZone: "UTC" }).format(new Date(item.dueDate + "T12:00:00Z")) : item.dueAt ? new Intl.DateTimeFormat(i18n.language, { dateStyle: "medium", timeZone: item.timezone }).format(new Date(item.dueAt)) : t("pending.noDeadline");
  return <li className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg border border-[#1797ba]/20 bg-[#1797ba]/5"><Icon aria-hidden="true" className="size-5 text-[#11718c] dark:text-[#55bdd9]" /></span><div className="min-w-0 space-y-2"><p className="text-xs text-muted-foreground">{t(`pending.${item.kind}`)} · {item.projectName}</p><h2 className="break-words font-medium">{item.title}</h2><div className="flex flex-wrap items-center gap-2"><span className={badge}>{t(`pending.${item.stale ? "stale" : item.blocked && item.state === "open" ? "blocked" : item.state}`)}</span><span className="text-xs text-muted-foreground">{item.responsible || t("pending.unassigned")}</span></div></div></div><div className="flex flex-wrap items-center justify-between gap-4 sm:max-w-60 sm:flex-col sm:items-end"><p className={`flex items-center gap-1 text-xs ${item.state === "open" && item.dueAt && new Date(item.dueAt).getTime() < Date.now() ? "text-amber-700 dark:text-amber-300" : "text-muted-foreground"}`}><Clock3 aria-hidden="true" className="size-3 shrink-0" /><span>{due}{item.dueAt && ` · ${item.timezone}`}</span></p>{item.href ? <Button variant="outline" size="sm" asChild><Link to={item.href}>{t("pending.reviewSource")}<ArrowUpRight aria-hidden="true" className="size-3" /></Link></Button> : <Button variant="outline" size="sm" onClick={open}>{t("pending.openRequest")}<ArrowUpRight aria-hidden="true" className="size-3" /></Button>}</div></li>;
}
export function RequestDialog({ id, close }: { id: string; close: () => void }) {
  const { t, i18n } = useTranslation(); const scope = useDataScope(); const cache = useQueryClient(); const [page, setPage] = useState(1); const path = `/client-pending/${encodeURIComponent(id)}`;
  const [operation, setOperation] = useState<{ action: string; revision: number; key: string } | null>(null); const [reason, setReason] = useState("");
  const query = useQuery({ queryKey: ["client-request", scope, id, page], queryFn: async ({ signal }) => (await axios.get<{ data: Detail }>(path, { params: { page }, signal })).data.data });
  const refresh = () => { void cache.invalidateQueries({ queryKey: ["client-request"] }); void cache.invalidateQueries({ queryKey: ["client-pending"] }); };
  const mutate = useMutation({ mutationFn: () => axios.post(path, { ...operation, reason }), onSuccess: () => { setOperation(null); setReason(""); }, onSettled: refresh });
  const detail = query.data; const r = detail?.request; const date = (v: string) => new Date(v).toLocaleString(i18n.language);
  return <Dialog open onOpenChange={open => { if (!open && !mutate.isPending) close(); }}><DialogContent className={area}><DialogHeader><DialogTitle className="break-words pe-5">{r?.title || t("pending.openRequest")}</DialogTitle><DialogDescription>{detail?.project.name || t("pending.loading")}</DialogDescription></DialogHeader>
    {query.isPending ? <p role="status">{t("pending.loading")}</p> : query.isError ? <div role="alert"><p>{t("pending.error")}</p><Button variant="outline" onClick={() => void query.refetch()}>{t("pending.refresh")}</Button></div> : r && detail && <div className="space-y-5">
      <div className="flex flex-wrap gap-2"><span className={badge}>{t(`pending.${r.kind}`)}</span><span className={badge}>{t(`pending.${r.state}`)}</span>{r.due_date && <span className={badge}>{r.due_date} · {r.timezone}</span>}</div>
      <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{r.description}</p>
      {detail.stale && <p role="status" className="text-sm text-amber-700 dark:text-amber-300">{t("pending.clientChanged")}</p>}
      {!!detail.dependencies.length && <div className="space-y-2 rounded-lg border border-border bg-secondary/30 p-3"><h3 className="text-sm font-medium">{t("pending.dependencies")}</h3><ul className="space-y-1">{detail.dependencies.map(d => <li key={d.id} className="break-words text-sm">{d.title} · {t(`pending.${d.state}`)}</li>)}</ul>{detail.blocked && <p className="text-xs text-muted-foreground">{t("pending.blockedNote")}</p>}</div>}
      {detail.canRespond && !detail.stale && <ResponseForm key={`${r.id}:${r.cycle}`} request={r} blocked={detail.blocked} refresh={refresh} />}
      {detail.canManage && <div className="space-y-3 border-t border-border pt-4"><div className="flex flex-wrap gap-2">{(r.state === "answered" && !detail.stale && !detail.blocked ? ["complete"] : []).concat(["open", "answered"].includes(r.state) ? ["cancel"] : [], ["answered", "completed", "cancelled"].includes(r.state) && !detail.stale ? ["reopen"] : []).map(action => <Button key={action} variant={action === "complete" ? "default" : "outline"} onClick={() => { setOperation({ action, revision: r.revision, key: crypto.randomUUID() }); setReason(""); }}>{t(`pending.${action}`)}</Button>)}</div>{operation && <form className="space-y-3 rounded-lg border border-border p-3" onSubmit={e => { e.preventDefault(); mutate.mutate(); }}><label className="block text-sm">{t(operation.action === "complete" ? "pending.note" : "pending.reason")}<textarea className={field} required={operation.action !== "complete"} maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} /></label><p className="text-xs text-muted-foreground">{t("pending.sharedNote")}</p><Button disabled={mutate.isPending} type="submit">{t(`pending.${operation.action}`)}</Button><Button type="button" variant="ghost" onClick={() => setOperation(null)}>{t("pending.close")}</Button></form>}{mutate.isError && <p role="alert" className="text-sm text-destructive">{t("pending.versionError")}</p>}</div>}
      <section className="space-y-3 border-t border-border pt-4"><h3 className="font-medium">{t("pending.responses")}</h3>{!detail.responses.length && <p className="text-sm text-muted-foreground">{t("pending.noResponses")}</p>}{detail.responses.map(response => <article key={response.id} className="space-y-3 rounded-lg border border-border p-3"><time className="text-xs text-muted-foreground" dateTime={response.created_at}>{date(response.created_at)}</time>{response.message && <p className="whitespace-pre-wrap break-words text-sm">{response.message}</p>}<dl className="space-y-3">{Object.entries(response.answers).map(([key, value]) => <div key={key}><dt className="break-words text-xs text-muted-foreground">{r.questions.find(q => q.id === key)?.label ?? key}</dt><dd className="whitespace-pre-wrap break-words text-sm">{value || "—"}</dd></div>)}</dl>{response.attachments.map(f => <a key={f.id} className="flex items-center gap-2 break-all text-sm text-[#11718c] underline dark:text-[#55bdd9]" href={/^https:\/\//.test(f.url) ? f.url : undefined} target="_blank" rel="noopener noreferrer"><Paperclip aria-hidden="true" className="size-4 shrink-0" />{f.name}</a>)}</article>)}{(page > 1 || detail.hasMoreResponses) && <div className="flex justify-between gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>{t("pending.previous")}</Button><Button variant="outline" disabled={!detail.hasMoreResponses} onClick={() => setPage(page + 1)}>{t("pending.next")}</Button></div>}</section>
      <details className="border-t border-border pt-3"><summary className="cursor-pointer text-sm">{t("pending.history")}</summary><ul className="mt-3 space-y-3">{detail.events.map(e => <li key={e.id} className="text-xs"><p>{t(`pending.events.${e.action}`)} · {e.actor} · {date(e.created_at)}</p>{e.reason && <p className="mt-1 whitespace-pre-wrap break-words text-muted-foreground">{e.reason}</p>}</li>)}</ul></details>
      {detail.canManage && <details className="border-t border-border pt-3"><summary className="cursor-pointer text-sm">{t("pending.reminders")}</summary><p className="mt-2 text-xs text-muted-foreground">{t("pending.reminderNote")}</p>{detail.reminders.map(v => <p key={v.id} className="mt-2 text-xs">{date(v.created_at)} · {t(`pending.reminderStates.${v.outcome}`)}</p>)}</details>}
    </div>}
  </DialogContent></Dialog>;
}
function ResponseForm({ request: r, blocked, refresh }: { request: Request; blocked: boolean; refresh: () => void }) {
  const { t } = useTranslation(); const scope = useDataScope(); const [message, setMessage] = useState(""); const [answers, setAnswers] = useState<Record<string, string>>({}); const [fileIds, setFileIds] = useState<string[]>([]); const [version] = useState(r.revision); const [key, setKey] = useState(crypto.randomUUID());
  const path = `/client-pending/${encodeURIComponent(r.id)}`;
  const files = useQuery({ queryKey: ["pending-files", scope, r.id], queryFn: async () => (await axios.get<{ data: { id: string; name: string }[] }>(`${path}/files`)).data.data });
  const upload = useMutation({ mutationFn: async (file: File) => { if (file.size > 10 * 1024 * 1024) throw new Error("FILE_TOO_LARGE"); const body = new FormData(); body.append("file", file); body.append("projectId", r.project_id); return (await axios.post<{ data: { fileId: string } }>(`/clients/${encodeURIComponent(r.client_id)}/media`, body)).data.data; }, onSuccess: result => { setFileIds(ids => [...new Set([...ids, result.fileId])]); void files.refetch(); } });
  const submit = useMutation({ mutationFn: () => axios.post(path, { key, revision: version, action: "respond", message, answers, fileIds }), onSuccess: refresh, onError: refresh });
  const changed = () => { setKey(crypto.randomUUID()); submit.reset(); };
  return <form className="space-y-4 rounded-lg border border-[#1797ba]/25 bg-[#1797ba]/5 p-4" onSubmit={e => { e.preventDefault(); if (!submit.isPending && !blocked) submit.mutate(); }}><h3 className="font-medium">{t("pending.yourResponse")}</h3><fieldset disabled={blocked || submit.isPending || upload.isPending} className="space-y-4">
    {r.questions.map(q => <label key={q.id} className="block text-sm">{q.label}{q.required && " *"}{q.type === "choice" ? <select className={field} required={q.required} value={answers[q.id] ?? ""} onChange={e => { setAnswers({ ...answers, [q.id]: e.target.value }); changed(); }}><option value="">{t("pending.choose")}</option>{q.options.map(o => <option key={o} value={o}>{o}</option>)}</select> : <textarea className={field} rows={3} maxLength={4000} required={q.required} value={answers[q.id] ?? ""} onChange={e => { setAnswers({ ...answers, [q.id]: e.target.value }); changed(); }} />}</label>)}
    <label className="block text-sm">{t(r.kind === "question" ? "pending.answer" : "pending.note")}<textarea className={field} rows={3} maxLength={4000} required={r.kind === "question"} value={message} onChange={e => { setMessage(e.target.value); changed(); }} /></label>
    <div className="space-y-2"><p className="text-sm font-medium">{t("pending.attachments")}</p>{files.data?.map(f => <label key={f.id} className="flex items-start gap-2 break-all text-sm"><input className="mt-1 shrink-0" type="checkbox" checked={fileIds.includes(f.id)} disabled={!fileIds.includes(f.id) && fileIds.length >= 10} onChange={e => { setFileIds(ids => e.target.checked ? [...ids, f.id] : ids.filter(id => id !== f.id)); changed(); }} />{f.name}</label>)}{files.isError && <p role="alert" className="text-sm">{t("pending.error")}</p>}<label className="block text-sm">{t("pending.upload")}<input className={`${field} file:me-2 file:rounded file:border-0 file:bg-secondary file:px-2 file:py-1`} type="file" accept=".jpg,.jpeg,.png,.gif,.webp,.pdf,.txt,.doc,.docx" disabled={fileIds.length >= 10} onChange={e => { const file = e.target.files?.[0]; if (file) { changed(); upload.mutate(file); } e.target.value = ""; }} /></label><p className="text-xs leading-relaxed text-muted-foreground">{t("pending.uploadNote")}</p></div>
    <Button type="submit" disabled={r.kind === "file" && !fileIds.length}>{t("pending.sendResponse")}</Button>
  </fieldset>{upload.isError && <p role="alert" className="text-sm text-destructive">{t("pending.uploadError")}</p>}{submit.isError && <p role="alert" className="text-sm text-destructive">{t("pending.versionError")}</p>}</form>;
}
function CreateDialog({ projectId, userId, close }: { projectId: string; userId: string; close: () => void }) {
  const { t } = useTranslation(); const cache = useQueryClient(); const scope = useDataScope(); const [id] = useState(crypto.randomUUID()); const [kind, setKind] = useState("question"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [questions, setQuestions] = useState<Question[]>([]); const [assignedTo, setAssignedTo] = useState(userId); const [dueDate, setDueDate] = useState(""); const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); const [dependencies, setDependencies] = useState<string[]>([]); const [reminderHours, setReminderHours] = useState(0); const [reminderChannel, setReminderChannel] = useState("internal");
  const options = useQuery({ queryKey: ["pending-options", scope, projectId], queryFn: async () => (await axios.get<{ data: { members: { id: string; name: string }[]; requests: { id: string; title: string }[]; hasClient: boolean } }>(`/client-pending/options/${encodeURIComponent(projectId)}`)).data.data });
  const create = useMutation({ mutationFn: () => axios.post("/client-pending", { id, projectId, kind, title, description, questions: kind === "briefing" ? questions : [], assignedTo, dueDate: dueDate || null, timezone, dependencies, reminderHours, reminderChannel }), onSuccess: () => { void cache.invalidateQueries({ queryKey: ["client-pending"] }); close(); } });
  const addQuestion = () => setQuestions(q => [...q, { id: crypto.randomUUID(), label: "", type: "text", required: true, options: [] }]);
  const updateQuestion = (id: string, values: Partial<Question>) => setQuestions(q => q.map(v => v.id === id ? { ...v, ...values } : v));
  return <Dialog open onOpenChange={open => { if (!open && !create.isPending) close(); }}><DialogContent className={area}><DialogHeader><DialogTitle>{t("pending.create")}</DialogTitle><DialogDescription>{t("pending.createNote")}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); if (!create.isPending) create.mutate(); }}><fieldset disabled={create.isPending || options.isPending || !options.data?.hasClient} className="space-y-4">
    <label className="block text-sm">{t("pending.kind")}<select className={field} value={kind} onChange={e => { setKind(e.target.value); if (e.target.value === "briefing" && !questions.length) addQuestion(); }}>{["question", "file", "briefing"].map(k => <option key={k} value={k}>{t(`pending.${k}`)}</option>)}</select></label>
    <label className="block text-sm">{t("pending.title")}<Input className="mt-1" required maxLength={160} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block text-sm">{t("pending.instructions")}<textarea className={field} required rows={3} maxLength={4000} value={description} onChange={e => setDescription(e.target.value)} /></label>
    {kind === "briefing" && <div className="space-y-3 border-s-2 border-[#1797ba]/30 ps-3">{questions.map((q, index) => <fieldset key={q.id} className="space-y-2 rounded-lg border border-border p-3"><legend className="px-1 text-xs">{t("pending.questionNumber", { number: index + 1 })}</legend><label className="block text-sm">{t("pending.questionLabel")}<Input required maxLength={200} value={q.label} onChange={e => updateQuestion(q.id, { label: e.target.value })} /></label><label className="block text-xs">{t("pending.answerType")}<select className={field} value={q.type} onChange={e => updateQuestion(q.id, { type: e.target.value as Question["type"], options: [] })}><option value="text">{t("pending.text")}</option><option value="choice">{t("pending.choice")}</option></select></label>{q.type === "choice" && <label className="block text-xs">{t("pending.choices")}<textarea className={field} required value={q.options.join("\n")} onChange={e => updateQuestion(q.id, { options: e.target.value.split("\n") })} /></label>}<div className="flex items-center justify-between gap-2"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={q.required} onChange={e => updateQuestion(q.id, { required: e.target.checked })} />{t("pending.required")}</label><Button type="button" variant="ghost" size="sm" disabled={questions.length === 1} onClick={() => setQuestions(v => v.filter(x => x.id !== q.id))}>{t("pending.remove")}</Button></div></fieldset>)}<Button type="button" variant="outline" disabled={questions.length >= 10} onClick={addQuestion}>{t("pending.addQuestion")}</Button></div>}
    <label className="block text-sm">{t("pending.assignee")}<select className={field} required value={assignedTo} onChange={e => setAssignedTo(e.target.value)}>{options.data?.members.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">{t("pending.dueDate")}<Input className="mt-1" type="date" required={reminderHours > 0} value={dueDate} onChange={e => setDueDate(e.target.value)} /></label><label className="block text-sm">{t("pending.timezone")}<Input className="mt-1" required maxLength={80} value={timezone} onChange={e => setTimezone(e.target.value)} /></label></div><p className="text-xs text-muted-foreground">{t("pending.deadlineNote")}</p>
    <details className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm">{t("pending.dependencies")}</summary><p className="my-2 text-xs text-muted-foreground">{t("pending.dependencyNote")}</p><div className="max-h-44 space-y-2 overflow-auto">{options.data?.requests.map(r => <label key={r.id} className="flex items-start gap-2 break-words text-sm"><input type="checkbox" className="mt-1" checked={dependencies.includes(r.id)} disabled={!dependencies.includes(r.id) && dependencies.length >= 10} onChange={e => setDependencies(v => e.target.checked ? [...v, r.id] : v.filter(id => id !== r.id))} />{r.title}</label>)}</div></details>
    <div className="space-y-3 rounded-lg border border-border bg-secondary/20 p-3"><label className="block text-sm">{t("pending.reminders")}<select className={field} value={reminderHours} onChange={e => setReminderHours(Number(e.target.value))}><option value={0}>{t("pending.noReminders")}</option>{[24, 48, 72, 168].map(hours => <option key={hours} value={hours}>{t("pending.everyHours", { hours })}</option>)}</select></label>{reminderHours > 0 && <label className="block text-sm">{t("pending.channel")}<select className={field} value={reminderChannel} onChange={e => setReminderChannel(e.target.value)}>{["internal", "email", "push"].map(v => <option key={v} value={v}>{t(`pending.${v}`)}</option>)}</select></label>}<p className="text-xs leading-relaxed text-muted-foreground">{t("pending.reminderNote")}</p></div>
    <Button type="submit">{t("pending.create")}</Button>
  </fieldset>{options.isError && <p role="alert" className="text-sm">{t("pending.error")}</p>}{options.data && !options.data.hasClient && <p role="status" className="text-sm">{t("pending.clientRequired")}</p>}{create.isError && <p role="alert" className="text-sm text-destructive">{t("pending.createError")}</p>}</form></DialogContent></Dialog>;
}
