import { useState } from "react";
import { Link, useParams } from "react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { GitPullRequestArrow, Plus, ArrowLeft, Paperclip, History, FileText, RefreshCw } from "lucide-react";
import { axios } from "@/configs/axios.config";
import { useUser } from "@/providers/user.provider";
import { useDataScope } from "@/hooks/useDataScope";
import { WorkspaceHeader, workspacePanel } from "@/components/ui/workspace-page";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";

type Version = { revision: number; classification: string; estimated_hours: string; amount?: string; currency?: string; end_date: string | null; note: string; decision: string | null; comment: string | null; created_at: string };
export type ScopeChange = { id: string; title: string; description: string; state: string; revision: number; requested_by: string; stale: boolean; cancellation_reason: string | null; created_at: string; source: { proposalId: string; title: string; version: string } | null; attachments: { id: string; versionId: string; name: string; url: string }[]; latest: Version | null; history: Version[]; hasMoreVersions: boolean; application: { appliedAt: string; taskId: string | null; dateApplied: boolean; billingDraft?: { id: string; amount: string; currency: string; description: string } | null } | null };
type Report = { items: ScopeChange[]; page: number; hasMore: boolean; project: { id: string; name: string; clientId: string | null }; canManage: boolean; canEstimate: boolean; canDecide: boolean };
type Action = "create" | "analysis" | "estimate" | "approve" | "reject" | "cancel" | "apply" | "history";
const fieldClass = "mt-1 block w-full min-w-0 rounded-md border border-border bg-background p-2 text-sm focus-visible:outline-2 focus-visible:outline-[#1797ba]";
const stateClass: Record<string, string> = { requested: "bg-blue-500/10 text-blue-700 dark:text-blue-300", analysis: "bg-violet-500/10 text-violet-700 dark:text-violet-300", awaiting: "bg-amber-500/10 text-amber-700 dark:text-amber-300", approved: "bg-green-500/10 text-green-700 dark:text-green-300", applied: "bg-[#1797ba]/10 text-[#11718c] dark:text-[#55bdd9]", rejected: "bg-red-500/10 text-red-700 dark:text-red-300", cancelled: "bg-secondary text-muted-foreground" };

export default function ScopeChangesPage() {
  const { id = "" } = useParams(); const scope = useDataScope(); const { data } = useUser(); const { t } = useTranslation(); const user = data?.user;
  const allowed = user && (user.role === "client" || ["superadmin", "subadmin"].includes(user.role) || (user.role === "user" && (user.isOrganizationOwner || user.isOrganizationManager)));
  return allowed ? <ScopeWorkspace key={JSON.stringify([scope, id])} projectId={id} portal={user.role === "client"} userId={user.id} /> : <p className="p-6">{t("scope.forbidden")}</p>;
}
function ScopeWorkspace({ projectId, portal, userId }: { projectId: string; portal: boolean; userId: string }) {
  const { t } = useTranslation(); const scope = useDataScope(); const [page, setPage] = useState(1); const [modal, setModal] = useState<{ action: Action; row?: ScopeChange } | null>(null);
  const path = `/projects/${encodeURIComponent(projectId)}/changes`;
  const query = useQuery({ queryKey: ["scope-changes", scope, projectId, page], queryFn: async ({ signal }) => (await axios.get<{ data: Report }>(path, { params: { page }, signal })).data.data });
  const report = query.data;
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6 text-foreground sm:px-6">
    <Link className="inline-flex items-center gap-2 text-sm text-[#11718c] hover:underline dark:text-[#55bdd9]" to={`${portal ? "/clients/projects/view" : "/dashboard/project/view"}/${encodeURIComponent(projectId)}`}><ArrowLeft className="size-4 rtl:rotate-180" aria-hidden="true" />{t("scope.back")}</Link>
    <WorkspaceHeader icon={GitPullRequestArrow} title={t("scope.title")} description={report?.project.name || t("scope.description")} actions={<Button disabled={!report?.project.clientId || query.isError} onClick={() => setModal({ action: "create" })}><Plus className="size-4" aria-hidden="true" />{t("scope.create")}</Button>} />
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_16rem]">
      <section className="min-w-0 space-y-4" aria-label={t("scope.requests")}>
        <div className="flex items-center justify-between gap-2"><h2 className="text-base font-medium">{t("scope.requests")}</h2><Button size="sm" variant="ghost" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw className="size-4" aria-hidden="true" />{t("scope.refresh")}</Button></div>
        {query.isPending ? <p role="status">{t("scope.loading")}</p> : query.isError ? <p role="alert" className="text-sm text-destructive">{t("scope.error")}</p> : report && <>
          {!report.project.clientId && <p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 text-sm">{t("scope.noClient")}</p>}
          {!report.items.length && <div className={`${workspacePanel} space-y-3 p-10 text-center`}><GitPullRequestArrow className="mx-auto size-8 text-[#1797ba]" aria-hidden="true" /><h3 className="font-medium">{t("scope.empty")}</h3><p className="text-sm text-muted-foreground">{t("scope.emptyHint")}</p></div>}
          {report.items.map(row => <article key={row.id} className={`${workspacePanel} min-w-0 overflow-hidden`}>
            <header className="flex flex-wrap items-start justify-between gap-3 border-b border-border bg-secondary/20 p-5"><h3 className="min-w-0 break-words text-base font-semibold">{row.title}</h3><span className={`rounded-md px-2 py-1 text-xs font-medium ${stateClass[row.state]}`}>{t(`scope.states.${row.state}`)}</span></header>
            <div className="space-y-4 p-5"><p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{row.description}</p>
              {row.source && <p className="break-words text-xs text-muted-foreground">{t("scope.source")}: {row.source.title} <span className="break-all">({row.source.proposalId})</span></p>}
              {row.attachments.length > 0 && <ul className="space-y-2">{row.attachments.map(file => <li key={file.id}><a className="inline-flex max-w-full items-center gap-2 text-sm text-[#11718c] underline dark:text-[#55bdd9]" href={/^https:\/\//.test(file.url) ? file.url : undefined} target="_blank" rel="noopener noreferrer"><Paperclip className="size-4 shrink-0" aria-hidden="true" /><span className="break-all">{file.name}</span></a></li>)}</ul>}
              {row.latest && <VersionSummary version={row.latest} />}
              {row.cancellation_reason && <p className="whitespace-pre-wrap break-words text-sm">{t("scope.reason")}: {row.cancellation_reason}</p>}
              {row.stale && <p role="status" className="text-sm text-amber-700 dark:text-amber-300">{t("scope.clientChanged")}</p>}
              {row.application && <div className="space-y-2 rounded-lg border border-[#1797ba]/20 bg-[#1797ba]/5 p-4 text-sm"><p className="font-medium">{t("scope.applied")}</p>{row.application.taskId && <p>{t("scope.taskCreated")}</p>}{row.application.dateApplied && <p>{t("scope.dateApplied")}</p>}{row.application.billingDraft && <div className="space-y-2 border-t border-[#1797ba]/20 pt-3"><p className="flex items-center gap-2 font-medium"><FileText className="size-4" aria-hidden="true" />{t("scope.billingDraft")}</p><p>{row.application.billingDraft.description}</p><p className="font-medium tabular-nums" dir="ltr">{row.application.billingDraft.amount} {row.application.billingDraft.currency}</p><p className="text-xs text-muted-foreground">{t("scope.billingNote")}</p><p className="break-all text-xs text-muted-foreground">{t("scope.reference")}: {row.application.billingDraft.id}</p></div>}</div>}
            </div>
            <footer className="flex flex-wrap gap-2 border-t border-border p-4">
              {row.revision > 0 && <Button variant="ghost" size="sm" onClick={() => setModal({ action: "history", row })}><History className="size-4" aria-hidden="true" />{t("scope.history")}</Button>}
              {!row.stale && <>
                {report.canManage && row.state === "requested" && <Button size="sm" variant="outline" onClick={() => setModal({ action: "analysis", row })}>{t("scope.analysis")}</Button>}
                {report.canEstimate && ["requested", "analysis", "awaiting", "rejected", "approved"].includes(row.state) && <Button size="sm" onClick={() => setModal({ action: "estimate", row })}>{t(row.revision ? "scope.revise" : "scope.estimate")}</Button>}
                {report.canDecide && row.state === "awaiting" && <><Button size="sm" onClick={() => setModal({ action: "approve", row })}>{t("scope.approve")}</Button><Button size="sm" variant="outline" onClick={() => setModal({ action: "reject", row })}>{t("scope.reject")}</Button></>}
                {report.canEstimate && row.state === "approved" && <Button size="sm" onClick={() => setModal({ action: "apply", row })}>{t("scope.apply")}</Button>}
              </>}
              {!["applied", "cancelled"].includes(row.state) && (report.canManage || (row.requested_by === userId && row.state !== "approved")) && <Button size="sm" variant="ghost" onClick={() => setModal({ action: "cancel", row })}>{t("scope.cancel")}</Button>}
            </footer>
          </article>)}
          <nav className="flex items-center justify-between gap-3" aria-label={t("scope.pagination")}><Button variant="outline" disabled={page === 1 || query.isFetching} onClick={() => setPage(page - 1)}>{t("scope.previous")}</Button><span className="text-sm tabular-nums">{page}</span><Button variant="outline" disabled={!report.hasMore || query.isFetching} onClick={() => setPage(page + 1)}>{t("scope.next")}</Button></nav>
        </>}
      </section>
      <aside className="space-y-4 rounded-xl border border-[#1797ba]/20 bg-[#1797ba]/5 p-5"><h2 className="text-sm font-semibold">{t("scope.flowTitle")}</h2><ol className="space-y-3 border-s-2 border-[#1797ba]/25 ps-4 text-sm">{["requested", "analysis", "awaiting", "approved", "applied"].map(state => <li key={state}>{t(`scope.states.${state}`)}</li>)}</ol><p className="border-t border-[#1797ba]/20 pt-4 text-xs leading-relaxed text-muted-foreground">{t("scope.flowNote")}</p></aside>
    </div>
    {modal && report && <Dialog open onOpenChange={open => { if (!open) setModal(null); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogTitle>{t(`scope.${modal.action}`)}</DialogTitle><DialogDescription>{modal.row?.title || t("scope.createHint")}</DialogDescription>{modal.action === "history" && modal.row ? <VersionHistory path={path} id={modal.row.id} /> : <ChangeForm key={`${modal.action}:${modal.row?.id ?? "new"}`} action={modal.action} row={modal.row} path={path} projectId={projectId} clientId={report.project.clientId} close={() => setModal(null)} />}</DialogContent></Dialog>}
  </main>;
}
function VersionSummary({ version }: { version: Version }) {
  const { t } = useTranslation();
  return <section className="space-y-3 rounded-lg border border-border bg-secondary/20 p-4"><div className="flex flex-wrap justify-between gap-2 text-xs font-medium"><span>{t("scope.version")} {version.revision}</span><span>{t(`scope.${version.classification}`)}</span></div><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">{t("scope.hours")}</dt><dd className="mt-1 font-medium tabular-nums">{version.estimated_hours}</dd></div>{version.amount !== undefined && <div><dt className="text-xs text-muted-foreground">{t("scope.price")}</dt><dd className="mt-1 font-medium tabular-nums" dir="ltr">{version.amount} {version.currency}</dd></div>}<div><dt className="text-xs text-muted-foreground">{t("scope.endDate")}</dt><dd className="mt-1 font-medium">{version.end_date || t("scope.noDateChange")}</dd></div></dl><p className="whitespace-pre-wrap break-words text-sm">{version.note}</p>{version.decision && <p className="text-sm font-medium">{t(`scope.states.${version.decision}`)}</p>}{version.comment && <p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{version.comment}</p>}</section>;
}
function VersionHistory({ path, id }: { path: string; id: string }) {
  const { t } = useTranslation(); const scope = useDataScope(); const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: ["scope-changes", scope, id, "versions", page], queryFn: async ({ signal }) => (await axios.get<{ data: Report }>(path, { params: { changeId: id, versionPage: page }, signal })).data.data });
  return <div className="space-y-4">{query.isPending ? <p>{t("scope.loading")}</p> : query.isError ? <p role="alert">{t("scope.error")}</p> : query.data?.items[0]?.history.map(version => <VersionSummary key={version.revision} version={version} />)}<div className="flex justify-between gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>{t("scope.previous")}</Button><Button variant="outline" disabled={!query.data?.items[0]?.hasMoreVersions} onClick={() => setPage(page + 1)}>{t("scope.next")}</Button></div></div>;
}
function ChangeForm({ action, row, path, projectId, clientId, close }: { action: Action; row?: ScopeChange; path: string; projectId: string; clientId: string | null; close: () => void }) {
  const { t } = useTranslation(); const cache = useQueryClient(); const [id] = useState(() => crypto.randomUUID());
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [files, setFiles] = useState<{ id: string; name: string }[]>([]); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState(false);
  const [classification, setClassification] = useState(row?.latest?.classification || "additional"); const [hours, setHours] = useState(row?.latest?.estimated_hours || ""); const [amount, setAmount] = useState(row?.latest?.amount || ""); const [currency, setCurrency] = useState(row?.latest?.currency || ""); const [endDate, setEndDate] = useState(row?.latest?.end_date || ""); const [note, setNote] = useState(row?.latest?.note || ""); const [reason, setReason] = useState("");
  const [createTask, setCreateTask] = useState(false); const [prepareBilling, setPrepareBilling] = useState(false); const [applyDate, setApplyDate] = useState(false); const [confirm, setConfirm] = useState(false);
  const mutation = useMutation({ mutationFn: async () => {
    if (action === "create") return axios.post(path, { id, title, description, fileIds: files.map(file => file.id) });
    const base = { revision: row!.revision };
    const payload = action === "estimate" ? { ...base, action, classification, estimatedHours: hours, amount: classification === "included" ? "0" : amount, currency, endDate: endDate || null, note } : action === "approve" || action === "reject" ? { ...base, action: "decide", state: action === "approve" ? "approved" : "rejected", comment: reason } : action === "apply" ? { ...base, action, createTask, prepareBilling, applyDate, confirm } : action === "cancel" ? { ...base, action, reason } : { ...base, action };
    return axios.post(`${path}/${encodeURIComponent(row!.id)}`, payload);
  }, onSuccess: close, onSettled: () => { void cache.invalidateQueries({ queryKey: ["scope-changes"] }); void cache.invalidateQueries({ queryKey: ["projects"] }); } });
  const errorCode = (mutation.error as { response?: { data?: { code?: string } } } | null)?.response?.data?.code;
  return <form className="space-y-4" onSubmit={event => { event.preventDefault(); if (!mutation.isPending && !uploading) mutation.mutate(); }}><fieldset disabled={mutation.isPending || uploading} className="space-y-4">
    {action === "create" && <><label className="block text-sm">{t("scope.requestTitle")}<Input className="mt-1" required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} /></label><label className="block text-sm">{t("scope.requestDescription")}<textarea className={fieldClass} required rows={4} maxLength={4000} value={description} onChange={e => setDescription(e.target.value)} /></label><label className="block text-sm">{t("scope.attachments")}<Input className="mt-1" type="file" disabled={files.length >= 5 || !clientId} onChange={async e => {
      const file = e.target.files?.[0]; if (!file || !clientId) return; e.target.value = ""; setUploading(true); setUploadError(false);
      try { const body = new FormData(); body.append("file", file); body.append("projectId", projectId); const response = await axios.post<{ data: { fileId: string; fileName: string } }>(`/clients/${encodeURIComponent(clientId)}/media`, body); setFiles(current => [...current, { id: response.data.data.fileId, name: response.data.data.fileName }]); } catch { setUploadError(true); } finally { setUploading(false); }
    }} /></label><p className="text-xs text-muted-foreground">{t("scope.fileNote")}</p>{uploading && <p role="status">{t("scope.uploading")}</p>}{uploadError && <p role="alert" className="text-sm text-destructive">{t("scope.uploadError")}</p>}{files.map(file => <div key={file.id} className="flex items-center justify-between gap-2 text-sm"><span className="min-w-0 break-all">{file.name}</span><Button type="button" variant="ghost" onClick={() => setFiles(files.filter(f => f.id !== file.id))}>{t("scope.remove")}</Button></div>)}</>}
    {action === "estimate" && <><label className="block text-sm">{t("scope.classification")}<select className={fieldClass} value={classification} onChange={e => setClassification(e.target.value)}><option value="additional">{t("scope.additional")}</option><option value="included">{t("scope.included")}</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">{t("scope.hours")}<Input className="mt-1" required inputMode="decimal" pattern="[0-9]{1,8}(\.[0-9]{1,2})?" value={hours} onChange={e => setHours(e.target.value)} /></label><label className="text-sm">{t("scope.currency")}<Input className="mt-1" required maxLength={3} pattern="[A-Z]{3}" placeholder="BRL" value={currency} onChange={e => setCurrency(e.target.value.toUpperCase())} /></label>{classification === "additional" && <label className="text-sm">{t("scope.price")}<Input className="mt-1" required inputMode="decimal" pattern="[0-9]{1,8}(\.[0-9]{1,2})?" value={amount} onChange={e => setAmount(e.target.value)} /></label>}<label className="min-w-0 text-sm">{t("scope.endDate")}<Input className="mt-1 min-w-0" type="date" value={endDate} onChange={e => setEndDate(e.target.value)} /></label></div><label className="block text-sm">{t("scope.estimateNote")}<textarea className={fieldClass} required rows={3} maxLength={4000} value={note} onChange={e => setNote(e.target.value)} /></label><p className="text-xs text-muted-foreground">{t("scope.revisionNote")}</p></>}
    {(action === "approve" || action === "reject") && row?.latest && <VersionSummary version={row.latest} />}
    {["approve", "reject", "cancel"].includes(action) && <label className="block text-sm">{t(action === "approve" ? "scope.comment" : "scope.reason")}<textarea required={action !== "approve"} className={fieldClass} rows={3} maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} /></label>}
    {action === "apply" && <><p className="text-sm text-muted-foreground">{t("scope.applicationNote")}</p>{(["createTask", "prepareBilling", "applyDate"] as const).map((key, index) => <label key={key} className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={[createTask, prepareBilling, applyDate][index]} disabled={(key === "prepareBilling" && !(row?.latest?.classification === "additional" && Number(row.latest.amount) > 0)) || (key === "applyDate" && !row?.latest?.end_date)} onChange={e => [setCreateTask, setPrepareBilling, setApplyDate][index](e.target.checked)} />{t(`scope.${key}`)}</label>)}<p className="text-xs text-muted-foreground">{t("scope.billingNote")}</p></>}
    {["approve", "apply"].includes(action) && <label className="flex items-start gap-3 border-t border-border pt-4 text-sm"><input type="checkbox" className="mt-1" required checked={confirm} onChange={e => setConfirm(e.target.checked)} />{t(action === "approve" ? "scope.confirmApproval" : "scope.confirmApplication")}</label>}
    <Button type="submit" disabled={action === "apply" && !createTask && !prepareBilling && !applyDate}>{t(mutation.isPending ? "scope.saving" : `scope.${action}`)}</Button>
  </fieldset>{mutation.isError && <p role="alert" className="text-sm text-destructive">{t(`scope.errors.${errorCode}`, { defaultValue: t("scope.saveError") })}</p>}</form>;
}
