import {useEffect,useRef,useState} from 'react';
import {useUser} from '@/providers/user.provider';
import {Link} from 'react-router';
import {useTranslation} from 'react-i18next';
import {Loader2} from 'lucide-react';
import {axios} from '@/configs/axios.config';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {WeeklyProjectSummaryResponse} from '@/hooks/useWeeklyProjectSummary';
import type {ProjectInsights} from '@/hooks/useProjectInsights';

// Preserve the original reports, but only request them after an explicit click.
export function AgentReports({kind}:{kind:'weekly'|'insights'}){
 const {t,i18n}=useTranslation();const {data:userData}=useUser();const projectHref=(id:string)=>`${userData?.user.role==='viewer'?'/viewer/projects':'/dashboard/project/view'}/${encodeURIComponent(id)}`;const [busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [weekly,setWeekly]=useState<WeeklyProjectSummaryResponse['data']|null>(null),[insights,setInsights]=useState<ProjectInsights|null>(null);const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>active.current?.abort(),[]);
 async function generate(){if(active.current)return;const controller=new AbortController();active.current=controller;setBusy(true);setFailed(false);try{
  const response=await axios.get(kind==='weekly'?'/ai/weekly-summary':'/ai/project-insights',{params:kind==='weekly'&&from&&to?{startDate:from,endDate:to}:undefined,signal:controller.signal,timeout:120000});
  if(!response.data?.success||!response.data.data)throw Error('Invalid report');if(kind==='weekly')setWeekly(response.data.data);else setInsights(response.data.data);
 }catch{if(!controller.signal.aborted)setFailed(true);}finally{active.current=null;setBusy(false);}}
 return <section className="space-y-4"><h3 className="text-lg font-semibold">{t(`hub.${kind}`)}</h3><p className="text-sm leading-6 text-muted-foreground">{t(`hub.${kind}Note`)}</p>
  <form className="space-y-4" onSubmit={e=>{e.preventDefault();void generate();}}>{kind==='weekly'&&<div className="grid grid-cols-2 gap-3"><label className="min-w-0 text-xs">{t('agent.startDate')}<Input type="date" value={from} disabled={busy} onChange={e=>setFrom(e.target.value)}/></label><label className="min-w-0 text-xs">{t('agent.endDate')}<Input type="date" value={to} disabled={busy} onChange={e=>setTo(e.target.value)}/></label></div>}<Button disabled={busy||(kind==='weekly'&&(Boolean(from)!==Boolean(to)||Boolean(from&&to&&from>to)))}>{busy&&<Loader2 className="size-4 animate-spin"/>}{t('agent.generate')}</Button></form>
  {failed&&<p role="alert" className="text-sm text-destructive">{t('agent.failed')}</p>}
  {weekly&&<div className="space-y-4 text-sm"><p className="text-xs text-muted-foreground">{new Date(weekly.period.start).toLocaleDateString(i18n.language)} — {new Date(weekly.period.end).toLocaleDateString(i18n.language)}</p><dl className="grid grid-cols-2 gap-3">{[['projects',weekly.metrics.totalProjects],['completed',weekly.metrics.completedTasks],['hours',weekly.metrics.totalHours],['billable',weekly.metrics.billableHours]].map(([label,value])=><div className="rounded-lg border p-3" key={label}><dt className="text-xs text-muted-foreground">{t(`hub.${label}`)}</dt><dd className="mt-1 text-lg font-semibold tabular-nums">{Number(value).toLocaleString(i18n.language)}</dd></div>)}</dl><p className="whitespace-pre-wrap leading-7">{weekly.summary}</p><ul className="list-disc space-y-2 ps-5">{[...weekly.highlights,...weekly.recommendations].map((v,i)=><li key={i}>{v}</li>)}</ul><div className="space-y-3">{weekly.projectBreakdown.map((p,i)=><article key={i} className="rounded-lg border p-3"><h4 className="font-semibold">{p.projectName}</h4><p className="mt-1 leading-6 text-muted-foreground">{p.summary}</p><p className="mt-2 text-xs tabular-nums">{p.progress}% · {p.hoursSpent.toLocaleString(i18n.language)} h</p></article>)}</div></div>}
  {insights&&<div className="space-y-4 text-sm"><dl className="grid grid-cols-2 gap-3">{[['onTrack',insights.timelinePredictions.projectsOnTrack],['delayed',insights.timelinePredictions.projectsDelayed],['atRisk',insights.timelinePredictions.projectsAtRisk],['completed',insights.summary.completedTasks]].map(([label,value])=><div className="rounded-lg border p-3" key={label}><dt className="text-xs text-muted-foreground">{t(`hub.${label}`)}</dt><dd className="mt-1 text-lg font-semibold tabular-nums">{Number(value).toLocaleString(i18n.language)}</dd></div>)}</dl>{(['urgentTasks','overdueTasks'] as const).map(kind=>insights.priorityInsights[kind].length>0&&<section key={kind}><h4 className="mb-2 font-semibold">{t(`hub.${kind}`)}</h4><ul className="space-y-2">{insights.priorityInsights[kind].map(task=><li key={task.taskId}><Link className="text-primary hover:underline" to={projectHref(task.projectId)}>{task.title}</Link></li>)}</ul></section>)}<ul className="list-disc space-y-2 ps-5">{insights.priorityInsights.recommendations.map((v,i)=><li key={i}>{v}</li>)}</ul>{[...insights.riskAnalysis.highRiskProjects,...insights.riskAnalysis.mediumRiskProjects,...insights.riskAnalysis.lowRiskProjects].map(p=><article key={p.projectId} className="rounded-lg border p-3"><Link to={projectHref(p.projectId)} className="font-semibold text-primary hover:underline">{p.projectName}</Link><p className="mt-2 text-xs tabular-nums">{t('hub.riskIndex')}: {p.riskScore}/100</p><ul className="mt-2 space-y-1 text-muted-foreground">{p.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul></article>)}</div>}
 </section>;
}
